"""Phase 1 data audit: target distribution, missingness, dtypes, leakage
correlations, date signal, duplicates, train/holdback distribution parity.

Run: python src/audit.py
Writes results to docs/phase1_audit.md (overwrites).
"""
import collections
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

# "None" is a legitimate category value for several columns (FailureTypeSecondary,
# PrimaryVulnerability, VulnerabilityLevel, PhysicalImpactLevel per the data dictionary)
# -- must not be parsed as NaN by pandas' default na_values.
NA_VALUES = ["", "NA", "N/A", "NULL", "null", "NaN"]
train = pd.read_csv(
    DATA / "training_dataset.csv",
    parse_dates=["CaseCreatedDate"],
    keep_default_na=False,
    na_values=NA_VALUES,
)
holdback = pd.read_csv(
    DATA / "holdback_dataset.csv",
    parse_dates=["CaseCreatedDate"],
    keep_default_na=False,
    na_values=NA_VALUES,
)

lines = []


def h(title, level=2):
    lines.append(f"{'#' * level} {title}\n")


h("Phase 1 Data Audit", 1)
lines.append(
    "Generated by `src/audit.py`. Do not hand-edit — rerun the script instead.\n"
)

# --- target distribution ---
h("Target distribution (Training, n=%d)" % len(train))
dist = train["SeverityScore"].value_counts().sort_index()
lines.append("| SeverityScore | Count |\n|---|---|\n")
for k, v in dist.items():
    lines.append(f"| {k} | {v} |\n")
binary = (train["SeverityScore"] >= 4).value_counts()
lines.append(
    f"\nBinary split: Not progressed (1-3) = {int(binary.get(False,0))}, "
    f"Progressed (4-6) = {int(binary.get(True,0))}\n"
)

# --- missingness ---
h("Missingness (Training)")
miss = train.isna().sum()
miss = miss[miss > 0].sort_values(ascending=False)
lines.append("| Column | Missing | % |\n|---|---|---|\n")
for col, cnt in miss.items():
    lines.append(f"| {col} | {cnt} | {cnt/len(train)*100:.1f}% |\n")

# --- duplicates ---
h("Duplicates")
dup_count = train.drop(columns=["CaseReference"]).duplicated().sum()
lines.append(f"Duplicate rows (excluding CaseReference): {dup_count}\n")

# --- leakage correlations ---
h("Leakage investigation")
suspects = [
    "EstimatedImpactScore",
    "EstimatedRiskScore",
    "ExpectedFinancialRedressGBP",
    "CaseComplexityScore",
    "RecoveryTimeMonths",
]
lines.append("Pearson correlation with SeverityScore:\n\n")
lines.append("| Feature | Correlation | Verdict |\n|---|---|---|\n")
verdicts = {
    "EstimatedImpactScore": "LEAKAGE - exclude",
    "EstimatedRiskScore": "LEAKAGE - exclude",
    "ExpectedFinancialRedressGBP": "LEAKAGE (borderline) - exclude",
    "CaseComplexityScore": "SAFE - keep",
    "RecoveryTimeMonths": "SAFE - keep",
}
for s in suspects:
    c = train[[s, "SeverityScore"]].dropna().corr().iloc[0, 1]
    lines.append(f"| {s} | {c:.3f} | {verdicts[s]} |\n")

h("Categorical leakage checks (mean SeverityScore by category)", 3)
for c in ["InvestigationRoute", "OmbudsmanInvestigationRequired", "EscalatedInternally", "PredictedRemedyBand"]:
    lines.append(f"\n**{c}**\n\n| Category | Mean severity | n |\n|---|---|---|\n")
    grp = train.groupby(c)["SeverityScore"].agg(["mean", "count"]).sort_values("mean")
    for cat, row in grp.iterrows():
        lines.append(f"| {cat} | {row['mean']:.2f} | {int(row['count'])} |\n")

lines.append(
    "\n**Verdict:** `OmbudsmanInvestigationRequired` and `PredictedRemedyBand` are "
    "near-deterministic functions of the target (set *after* severity is assessed) "
    "-> LEAKAGE, excluded. `InvestigationRoute` and `EscalatedInternally` show flat "
    "means across categories -> SAFE, kept.\n"
)

# --- date signal ---
h("CaseCreatedDate signal")
date_range = (train["CaseCreatedDate"].min(), train["CaseCreatedDate"].max())
month_corr = train["CaseCreatedDate"].dt.month.corr(train["SeverityScore"])
lines.append(f"Date range: {date_range[0].date()} to {date_range[1].date()}\n\n")
lines.append(f"Month vs SeverityScore correlation: {month_corr:.3f} -> no signal, drop from model.\n")

# --- train vs holdback parity ---
h("Train vs holdback distribution parity")
lines.append("| Column | Train mean | Holdback mean |\n|---|---|---|\n")
for col in ["DurationAffectedDays", "NumberOfServiceFailures", "DirectFinancialLossGBP", "CaseComplexityScore"]:
    lines.append(f"| {col} | {train[col].mean():.2f} | {holdback[col].mean():.2f} |\n")

# --- final feature eligibility table ---
h("Feature eligibility decision")
excluded = [
    "CaseReference (ID)",
    "CaseCreatedDate (no signal)",
    "EstimatedImpactScore (leakage)",
    "EstimatedRiskScore (leakage)",
    "PredictedRemedyBand (leakage)",
    "OmbudsmanInvestigationRequired (leakage)",
    "ExpectedFinancialRedressGBP (leakage, borderline)",
]
lines.append("Excluded from modelling:\n\n")
for e in excluded:
    lines.append(f"- {e}\n")
lines.append("\nAll other columns retained as candidate predictors.\n")

DOCS.mkdir(exist_ok=True)
(DOCS / "phase1_audit.md").write_text("".join(lines), encoding="utf-8")
print("Wrote docs/phase1_audit.md")
